name: My First Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  first-pipeline:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t hello-world-nginx:v1 .

      - name: Run Docker container
        run: |
          docker run -d -p 8090:80 --name hello-nginx hello-world-nginx:v1

      - name: Verify container is running
        run: docker ps
