name: My First Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  first-pipeline:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with branch and commit-sha tags
        run: |
          IMAGE_NAME=hello-world-nginx
          BRANCH=$(echo "${GITHUB_REF#refs/heads/}" | tr '/' '-')
          SHA=${GITHUB_SHA::7}
          docker build -t $IMAGE_NAME:$BRANCH-$SHA .

      - name: Run Docker container
        run: |
          docker run -d -p 8090:80 --name hello-nginx hello-world-nginx:v1

      - name: Verify container is running
        run: docker ps
